// Secrets/vars not declared in wrangler.jsonc (set via `.env` locally,
// `wrangler secret put` in prod). Kept separate from env.d.ts since that
// file is regenerated by `wrangler types` and would drop this.
interface Env {
  BRAVE_API_KEY: string;
}
