/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 74fcfa02c7854e42c40ae2e15caadd67)
interface __BaseEnv_Env {
	AI: Ai;
	MeetingAgent: DurableObjectNamespace<import("./src/server").MeetingAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "MeetingAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
